### ISSUE TITLE
TXCO on STM32F4

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-org#38]

**Comment by ykoveos** [comment]
I was planing to have 32kHz with ST's smooth calibrator (~2ppm) (same technique used in D-TXCO), since we have good temperature sensors. The best TXCO at 32kHz is at 5ppm (?). You can have better at 12MHz (<2ppm), but we will have to keep the OSC running all the time.? 
Even if we use  better TXCO (<1ppm???) we wil have to calibrate, for the drift! We need GPS .. 1Hz pulse, since we will fire GPS for position calibration more often, time is not an issue

Does this GPS has separate signal for 1Hz? or we will use RX falling edge???  

I think we can have TXCO@32kHz, (need to check if 32kHz OSC accepts Ext. clock, i think it does) but this will not save us much
